[tool.ruff]
# Set the maximum line length. 88 is the standard set by Black.
line-length = 100

# Enable Pyflakes (F), pycodestyle (E, W), isort (I), and pyupgrade (UP) rule sets.
select = ["E", "W", "F", "I", "UP"]

# Exclude the virtual environment folder from checks.
exclude = [".venv"]

[tool.ruff.format]
# Use double quotes for strings.
quote-style = "double"
