version: '3.8'

services:
  postgres:
    image: postgres:13-alpine
    container_name: mattermost_postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: mattermost
      POSTGRES_USER: mattermost
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - mattermost_internal
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U mattermost"]
      interval: 30s
      timeout: 10s
      retries: 5

  mattermost:
    image: mattermost/mattermost-enterprise-edition:7.8
    container_name: mattermost_app
    restart: unless-stopped
    ports:
      - "8065:8065"
    environment:
      # Database settings
      MM_SQLSETTINGS_DRIVERNAME: postgres
      MM_SQLSETTINGS_DATASOURCE: postgres://mattermost:${POSTGRES_PASSWORD}@postgres:5432/mattermost?sslmode=disable&connect_timeout=10

      # Server settings - CORRECTED
      MM_SERVICESETTINGS_SITEURL: http://192.168.1.100:8065
      MM_SERVICESETTINGS_LISTENADDRESS: ":8065"
      MM_SERVICESETTINGS_CONNECTIONATTACHMENT: "local"
      MM_SERVICESETTINGS_ALLOWCORSFROM: "*"

      # WebSocket settings - FIXED
      MM_SERVICESETTINGS_WEBSOCKETURL: ""
      MM_SERVICESETTINGS_WEBSOCKETPORT: 8065
      MM_SERVICESETTINGS_WEBSOCKETSECUREPORT: 8065

      # Bot and webhook settings
      MM_SERVICESETTINGS_ENABLEBOTACCOUNTCREATION: "true"
      MM_SERVICESETTINGS_ENABLEINCOMINGWEBHOOKS: "true"
      MM_SERVICESETTINGS_ENABLEOUTGOINGWEBHOOKS: "true"
      MM_SERVICESETTINGS_ENABLECOMMANDS: "true"

      # Plugin settings
      MM_PLUGINSETTINGS_ENABLE: "true"
      MM_PLUGINSETTINGS_ENABLEUPLOADS: "true"

      # Team settings
      MM_TEAMSETTINGS_ENABLETEAMCREATION: "true"
      MM_TEAMSETTINGS_ENABLEUSERCREATION: "true"

      # File settings
      MM_FILESETTINGS_ENABLEFILEATTACHMENTS: "true"
      MM_FILESETTINGS_MAXFILESIZE: 52428800

    volumes:
      - mattermost_data:/mattermost/data
      - mattermost_logs:/mattermost/logs
      - mattermost_config:/mattermost/config
    networks:
      - mattermost_internal
    depends_on:
      postgres:
        condition: service_healthy

volumes:
  postgres_data:
  mattermost_data:
  mattermost_logs:
  mattermost_config:

networks:
  mattermost_internal:
    driver: bridge
