# ~/net-chatbot/database/docker-compose.yml
# PostgreSQL Service - Three-Tier Discovery Database

version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: netops-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-netops_db}
      POSTGRES_USER: ${POSTGRES_USER:-netops}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-netops_password}
      POSTGRES_INITDB_ARGS: "--auth-host=scram-sha-256"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d:ro
      - ./backups:/backups
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    networks:
      - netops-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER:-netops} -d ${POSTGRES_DB:-netops_db}"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    logging:
      driver: json-file
      options:
        max-size: "10m"
        max-file: "3"

networks:
  netops-network:
    driver: bridge
    name: netops-network

volumes:
  postgres_data:
    driver: local
    name: netops-postgres-data
